spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_b631d961d1878e0?user=b58acf17cba283
spring.datasource.username=b58acf17cba283
spring.datasource.password=c49397d0

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect